const EErrors = {
    SERVER_ERROR:1,
    INVALID_INPUT_ERROR:2,
    UPDATE_ERROR:3,
    DELETE_ERROR:4,
    MONGO_CONNECTION_ERROR:5,
    SOCKET_CONNECTION_ERROR:6,
    MAIL_SEND_ERROR:7,
}

export default EErrors